version: '3'

services:
  httpd:
    image: nginx 
    container_name: nginx
    depends_on:
      - php
    ports:
      - "8080:80"
      - "443:443"
    restart: always
    working_dir: /var/www
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    environment:
      - TZ=Asia/Taipei
    networks:
      - nginx-php
  php:
    build: ./.docker/php
    image: ri3567/php:7.2.2-fpm
    container_name: php
    restart: always
    environment:
      - TZ=Asia/Taipei
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./.docker/php/TZ.ini:/usr/local/etc/php/conf.d/TZ.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks: 
      - nginx-php

networks:
  nginx-php:
